version: '3'

services:
 nginx:
      image: nginx
      volumes:
          - ./code:/code
          - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf 
      ports:
          - "8080:80"
      restart: always
 php:
      image: php:7.2-fpm
      volumes:
          - ./code:/code
      restart: always

 composer:
     image: composer:1.6
     restart: always
     command:
           composer install
