version: '3'

services:
 nginx:
      image: nginx
      volumes:
          - ./src:/src
          - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf 
      ports:
          - "8080:80"
      restart: always
 php:
      build: ./conf/php/
      volumes:
          - ./src:/src
      restart: always
     

 composer:
     image: composer:1.6
     restart: always
     volumes:
          - ./src:/src
     working_dir: /src
     command: composer install
